export const EDIT_ABOUT_PAGE = 'EDIT_ABOUT_PAGE';
export const EDIT_CONTACT_PAGE = 'EDIT_CONTACT_PAGE';
export const EDIT_EDUCATION_PAGE_TITLE = 'EDIT_EDUCATION_PAGE_TITLE';
export const EDIT_PROJECT_PAGE_TITLE = 'EDIT_PROJECT_PAGE_TITLE';
export const EDIT_SKILL_PAGE_TITLE = 'EDIT_SKILL_PAGE_TITLE';
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
