export const EDIT_ABOUT_PAGE = 'EDIT_ABOUT_PAGE';
export const EDIT_CONTACT_PAGE = 'EDIT_CONTACT_PAGE';
export const LOGIN = 'LOGIN';
// Education Page Constants
export const EDIT_EDUCATION_PAGE_TITLE = 'EDIT_EDUCATION_PAGE_TITLE';
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
// Project Page Constants
export const EDIT_PROJECT_PAGE_TITLE = 'EDIT_PROJECT_PAGE_TITLE';
export const CREATE_PROJECT = 'CreREATE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
// Skill Page Constants
export const EDIT_SKILL_PAGE_TITLE = 'EDIT_SKILL_PAGE_TITLE';
export const CREATE_SKILL = 'CREATE_SKILL';
export const EDIT_SKILL = 'EDIT_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';
// Nav Constants
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_NAME = 'EDIT_NAME';
export const EDIT_COLORS = 'EDIT_COLORS';
// SOCIAL LINK CONSTANT
export const CREATE_SOCIAL_lINK = 'CREATE_SOCIAL_lINK';
export const EDIT_SOCIAL_lINK = 'EDIT_SOCIAL_lINK';
export const DELETE_SOCIAL_lINK = 'DELETE_SOCIAL_lINK';
